In [55]:
import numpy as np
from scipy.linalg import expm

In [9]:
def abs_exp(eig:list) -> float: #This is what we have in the bound
    return np.exp(np.max(np.abs(eig)))

def exp_abs(eig:list) -> float: #This is what we want
    return np.max(np.exp(-eig))

def compare(eig:list) -> bool:
    return abs_exp(eig)>= exp_abs(eig)

In [10]:
for _ in range(100):
    vector = np.random.rand(5)
    print(compare(vector))

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [19]:
def partition_function(eig:list) -> float:
    return sum(np.exp(-eig))
def gibbs_state(eig:list) -> float:
    return np.exp(-eig)/partition_function(eig)
def exp_norm_hamiltonian(eig:list) -> float:
    return np.exp(np.max(np.abs(eig)))/partition_function(eig)

In [18]:
sum(gibbs_state(vector))


1.0000000000000002

In [22]:
exp_norm_hamiltonian(vector)

0.5527586529692203

In [103]:
for _ in range(1):
    vector = np.random.rand(2)-0.5
    quant = exp_norm_hamiltonian(vector)
    if quant>1:
        print('This is an example')
        print(quant)
        print(sum(gibbs_state(vector)))
        print(vector)

In [138]:
N=3
for _ in range(100000):
    A = np.random.rand(3,3)-0.5
    A = A + A.T
    B = np.random.rand(3,3)-0.5
    B = B+B.T
    expA = expm(A)
    expAB = expm(A+B)
    w,v = np.linalg.eigh(expAB-expA)
    ww,vv = np.linalg.eigh(expA)
    www,vvv = np.linalg.eigh(B)
    quant = max(np.abs(w))
    bound = max(np.abs(ww)) * (np.exp(max(np.abs(www))) - 1 )
    if quant > bound:
        print(quant,bound)

In [146]:
N=3
for _ in range(10000):
    A = np.random.rand(3,3)-0.5
    A= A + A.T
    A = A @ A.T
    B = np.random.rand(3,3)-0.5
    B=B+B.T
    B = B@B.T

    normB , _ = np.linalg.eigh(B)
    print(normB)
    normB = max(np.abs(normB))
    quant = A@B@A@A@A + B@A@A@A@A +A@B@B@A
    quant,_ = np.linalg.eigh(quant)
    quant =  max(np.abs(quant))
    bound,_ = np.linalg.eigh( 2* normB * (A@A@A@A) + normB**2 * A@A )
    bound = max(np.abs(bound))
    if quant/bound - 1 > 1e-3:
        print(quant,bound)
    

[0.12631122 0.4506489  1.79157855]
[0.0185527  0.6331544  2.16355244]
[1.08831142e-03 2.16657404e-01 1.64895449e+00]
[0.00265065 0.39423893 1.73520001]
[0.00175781 0.15036369 1.16970668]
[0.04117354 0.29759292 1.99307305]
[0.02113204 0.76518471 2.16431858]
[0.11555162 0.75593473 1.0184332 ]
[0.08385767 0.13362269 0.6090531 ]
[0.10716177 0.23813717 0.87722943]
[0.07496089 0.31702142 0.46281228]
[0.36808678 0.56659872 1.42555381]
[0.06514375 0.30684197 0.79603472]
[0.12789961 0.6426877  1.06908794]
[0.00127908 1.03079086 1.17084621]
[0.01641888 0.99756335 1.06304637]
[0.22760369 0.73834978 1.8686988 ]
[0.04837658 0.64629363 1.58846881]
[0.20216873 0.56231865 1.53226864]
[0.04016539 0.56663521 1.62518171]
[0.12703173 0.22906582 0.47233387]
[0.14578267 1.33850287 1.51837266]
[0.4855997  1.305143   1.48075531]
[0.36808952 0.80115745 1.08846482]
[0.42020749 1.29423057 1.85872137]
[0.02196198 1.03525356 2.2717034 ]
[0.18334891 0.21360035 0.83707174]
[1.38418756e-03 5.31767711e-01 1.61380021e+

[3.78857120e-04 6.84456272e-02 1.19055034e+00]
[0.40516296 0.85761995 1.23916385]
[0.00993568 0.88535777 1.2140219 ]
[0.03671944 0.08188784 2.14537132]
[0.06047385 0.08809641 1.70215367]
[0.02219821 0.38994717 2.21037769]
[0.00185546 0.68986895 1.45893562]
[0.00826928 0.53565347 1.239558  ]
[0.00564077 0.41420214 0.76708386]
[0.01093606 0.40434062 1.96906622]
[0.12156743 0.28095954 0.78897895]
[0.01522469 1.59156015 1.69379998]
[0.0386316  0.17620407 0.55875636]
[0.01287884 0.25993739 1.88041989]
[0.24107111 0.66574584 1.64053721]
[0.16547582 0.24539244 1.4050458 ]
[0.09894578 0.44403216 1.63400438]
[0.06198016 0.99973553 1.75804791]
[0.1403952  0.42726946 2.01225534]
[5.14630600e-05 1.13373014e+00 1.32995741e+00]
[0.05974703 0.80459271 0.94088047]
[0.09888198 0.16556557 0.68800154]
[0.02961761 1.02442099 1.15702074]
[0.30349478 1.15182423 1.18914679]
[0.07410348 0.48372813 1.44976723]
[0.0045698  0.44644206 1.02994748]
[0.11414517 0.36577301 1.06526371]
[6.64568438e-05 3.28408496e-01 

[0.19630122 0.28646972 1.50752873]
[0.04257423 0.15810125 0.50647254]
[0.0207657  0.08006797 0.18286293]
[0.18831334 0.36924391 1.85448078]
[0.05866476 0.75541009 1.69993137]
[0.32461973 0.63958417 1.12606969]
[0.03762285 0.2752542  0.67821893]
[0.15335973 0.78871836 1.30132774]
[0.00972676 0.60451937 0.80073258]
[3.09906231e-04 4.44128936e-01 1.47059195e+00]
[0.46156559 0.83986544 0.9479652 ]
[0.04018274 0.1523628  0.61647776]
[1.50660027e-04 6.08042541e-01 1.41198277e+00]
[0.00380815 0.35658167 2.58866101]
[0.00358176 0.07994288 1.2684361 ]
[0.22656985 0.25292749 1.79225066]
[0.19914071 0.38007929 0.45098459]
[0.25228381 0.77310634 1.08849398]
[0.2741285  0.6395577  1.20379346]
[0.12956732 0.58219555 0.88388969]
[0.00072421 0.02310694 0.55780873]
[0.04745687 0.06543273 3.22293929]
[0.18564788 0.24557001 0.5733079 ]
[0.23872533 0.44557728 0.86683742]
[0.01702704 0.96489695 2.12428054]
[0.00317253 0.99510094 1.49505051]
[0.07892068 1.09780853 1.26816565]
[0.06548037 0.23206728 1.355434

[0.19278125 0.6935476  1.48732484]
[0.18309116 0.72704595 1.3144858 ]
[0.15706246 0.60084998 1.64692324]
[0.13848507 0.64573475 0.75979268]
[0.00273143 0.29314274 0.62942047]
[0.0519847  0.85062464 2.56850087]
[0.15673998 0.18342842 0.58150014]
[0.00442775 1.20497273 1.24611529]
[0.0460846  1.12227609 1.34132827]
[0.02351064 0.28313725 0.73881688]
[0.11349865 0.82816898 1.52029562]
[0.0445963  1.11551155 1.41543025]
[0.10817683 0.25668794 2.64341791]
[0.13882044 0.14712648 0.76132939]
[0.00572651 0.2639776  1.27789474]
[0.40567551 0.51241786 0.81217549]
[0.2016733  0.52405211 0.98443898]
[0.06202421 0.14593957 0.34170258]
[0.00338975 0.11150041 1.66841349]
[0.12688686 0.13160305 0.76477248]
[2.32673212e-04 1.01400076e+00 1.51234546e+00]
[0.11801757 0.63222214 0.71834121]
[0.01101487 0.10531029 1.84913788]
[0.0768996  1.16350445 1.25326621]
[0.00883057 0.0595179  1.39879842]
[0.06620281 0.68492136 0.79592438]
[0.04407105 0.20087006 0.57134935]
[0.14712977 0.17491035 0.76117961]
[0.09333

[0.02369518 0.3040164  1.81946573]
[0.2664364  0.35928757 0.94441818]
[0.04385476 0.62578083 0.81725578]
[0.49645459 0.72480801 1.01578957]
[0.17841667 1.64641082 2.21728012]
[0.00035574 0.11013211 0.32010539]
[0.02798808 0.19732669 1.94154798]
[0.03941993 0.58308415 0.94437911]
[0.00184199 0.91675002 1.38073196]
[0.07218879 0.57059574 1.130967  ]
[0.01043456 1.02058135 1.25796164]
[0.02374946 1.2909674  1.99729857]
[0.00241782 0.28350399 1.54533397]
[0.02296946 0.07178655 0.09692334]
[0.0592421  1.45917728 2.08572527]
[0.01800637 0.20709457 1.14590218]
[0.03910544 0.27252649 1.07280628]
[0.02204636 1.06264766 1.40037686]
[0.10473301 0.44472124 3.39325807]
[0.01140758 0.19210572 0.49625064]
[0.04088006 0.82059533 1.90195718]
[0.46878703 0.83308918 1.56944148]
[0.00199974 0.53492359 0.91328201]
[0.0017172  0.19049811 0.29851076]
[0.00362577 1.38612904 1.44021386]
[0.32322648 0.48881701 0.60372316]
[0.5026176  0.90336201 1.14503295]
[0.00415301 0.3953073  0.66973733]
[0.27407752 0.830313

[0.19207777 0.5626375  1.70212942]
[0.07270016 0.4943216  1.16981587]
[0.18722844 0.96968272 1.27828222]
[0.00699292 0.58107022 2.22346687]
[0.21247687 0.36225707 1.51969098]
[0.03857    0.23833725 2.93097265]
[0.08366092 0.13268312 2.12815482]
[0.06795518 0.35005407 0.55453577]
[0.16963579 0.68565437 1.32036012]
[0.09131774 0.91229864 1.11721647]
[0.02114953 1.0661566  1.63254084]
[0.02236829 0.97812642 1.51660914]
[0.0366796  0.15464124 2.2673677 ]
[0.14792633 0.26168925 1.16695352]
[0.16201319 0.54727959 0.94671144]
[0.10921628 0.47107723 2.48784261]
[0.01059467 1.33167141 1.70844057]
[0.12460329 0.57500499 0.61366275]
[0.01319812 0.19252067 1.55476612]
[0.05126144 0.20666558 1.22080202]
[2.00138957e-04 1.14747402e+00 1.52372120e+00]
[0.55438221 1.3317171  1.59989689]
[0.27862116 0.90240961 1.9446102 ]
[0.00215444 0.25457508 0.39236167]
[0.0035612  0.23621142 2.08821886]
[0.11703688 0.150152   1.13095348]
[0.06262725 0.7584471  1.68865329]
[0.17448796 0.39400558 1.67653846]
[0.05056

[0.05653535 0.10401267 1.02593961]
[0.01736406 0.12256675 1.5664334 ]
[2.32162461e-05 6.43915211e-01 2.06930823e+00]
[0.03760994 0.13366881 1.74935036]
[0.01923533 0.43556114 1.16366085]
[0.00475851 0.83873796 1.12467512]
[0.02037937 0.29971637 1.69811696]
[0.01594474 0.59046641 1.89909339]
[0.127761   0.34898684 0.98266211]
[0.13156795 0.18179293 0.98840874]
[0.02690765 0.22092014 2.06072286]
[0.33071861 0.81499254 1.05239893]
[0.06457261 0.31947755 0.6868362 ]
[0.06736725 0.87646241 1.73684931]
[2.28866388e-04 1.27088146e-02 9.41367710e-01]
[5.11796715e-04 2.09583622e-01 2.36215630e+00]
[0.00448688 0.09714908 1.11821911]
[0.00143735 0.46934747 0.76772871]
[0.01888247 0.53176991 0.8739731 ]
[0.05069749 0.63554415 0.93064835]
[0.13419543 0.46470147 0.50553412]
[0.18603063 0.47132211 1.0311835 ]
[0.04163899 0.33496    0.4802537 ]
[0.06333466 0.23677346 2.22080522]
[0.25439506 0.45121699 2.01660192]
[0.01980425 0.31661251 0.98936814]
[0.03620018 0.11406738 1.67252509]
[0.03515654 0.85185

[0.03542147 0.84830149 1.76567761]
[0.47913399 0.51901737 2.04683386]
[0.01550022 0.09194355 1.24950029]
[0.01019104 0.20100122 0.35781795]
[0.09412693 0.16124034 1.1832914 ]
[0.02673295 1.40233236 1.72626937]
[0.07255202 0.88254015 1.03156215]
[0.21470489 0.39236365 3.06421573]
[4.14101182e-05 3.71369134e-01 1.95329544e+00]
[0.05113673 0.87756881 1.23481703]
[0.06678284 0.21299894 2.50798331]
[0.69893213 0.83716007 1.29196208]
[0.07752982 0.32223613 1.25868291]
[0.19604593 0.75284482 1.14180629]
[0.30572468 0.51631953 1.39095711]
[0.11871469 0.56507899 2.201221  ]
[0.10249704 0.21672432 2.16526779]
[0.11218165 0.12166113 1.45731449]
[0.00918595 0.40987753 1.95499717]
[0.01836472 0.12870492 0.74017744]
[0.06373519 0.64971762 1.14003001]
[0.0704205  0.0941325  0.91752656]
[0.40311049 0.92678996 1.16327856]
[0.06032553 0.15059664 0.49104257]
[0.00908195 0.3180964  1.04724531]
[0.0014492  0.55556993 1.36253204]
[0.16226267 0.62330794 1.08690481]
[0.28937071 0.33503561 1.01711223]
[0.25659

[0.44648606 0.84040544 1.34729969]
[0.0003422  0.11195466 0.32574054]
[0.0308772  1.63807108 1.79609695]
[0.01777137 0.47118568 2.63202238]
[0.07865686 1.15167191 1.18338184]
[0.00403213 0.8294985  0.91789492]
[5.99560334e-04 5.92543706e-03 1.53613491e+00]
[0.0378245  0.06029455 0.95574486]
[0.05535822 0.71332284 0.83850812]
[0.01091536 0.67343614 1.1386145 ]
[0.02442189 0.5577395  1.43669021]
[1.52582522e-04 8.91520215e-02 9.23036334e-01]
[0.10699118 0.51523746 1.1137959 ]
[0.13569279 0.62032477 1.7030859 ]
[0.23097806 0.59152282 1.70220795]
[0.20615541 0.6194131  0.8858559 ]
[0.0866107  1.13626659 1.33025924]
[0.32300471 0.38722884 0.92751572]
[0.02970881 0.83269258 2.07871058]
[0.11827258 0.33131535 3.97679065]
[0.16946925 0.19569266 1.169694  ]
[0.01499435 0.49208173 1.25170307]
[0.08896009 0.20511377 3.50253732]
[0.2768708  0.94884125 1.35361696]
[0.13612882 0.68691511 0.89751068]
[0.00357422 0.40577871 1.05674423]
[0.02817046 0.83163034 1.48311774]
[0.03292224 0.59474287 0.809787

[0.00725982 0.35615758 2.55431329]
[0.00677776 0.70793806 1.56028537]
[0.02434316 1.02516047 1.18920451]
[0.0373267  0.49389808 1.12119412]
[0.4086462  0.95229644 1.45171824]
[0.05681186 0.11896714 0.40965001]
[0.05943969 0.81397755 1.0365702 ]
[0.03304852 0.2647249  3.59719557]
[0.0777799  0.49251646 0.62669037]
[0.03692689 0.62776897 0.89253518]
[0.02329514 0.29316923 0.9136401 ]
[0.04233528 0.25062937 0.25480161]
[0.00546561 0.22024583 0.96315068]
[0.03190617 0.60950058 1.06816904]
[0.04943173 0.85817458 2.33829915]
[0.09806182 0.94324251 1.34341055]
[0.00434174 0.06551423 1.55486601]
[4.77384624e-05 6.71424190e-01 1.01511524e+00]
[0.0461971  0.15407278 0.28828916]
4.009863457162644 3.986420480641682
[0.34711229 1.20088196 1.29075994]
[0.01820409 0.32921114 1.68464809]
[0.11390768 0.11829523 1.02037906]
[0.04970499 0.0502717  3.00340374]
[0.01479584 0.33925011 0.92318725]
[0.80507537 0.97588616 1.01917285]
[0.00853652 1.2913545  2.32064432]
[0.03677236 0.87150527 1.2185186 ]
[0.1561

[0.19482152 0.33439795 2.1437614 ]
[0.0345352  0.51341674 1.83122745]
[0.21350325 0.63938829 2.12986364]
[0.55636381 0.66952319 1.02773974]
[0.19682897 0.45850887 1.5721126 ]
[0.01061151 1.14019673 1.86934798]
[3.99065757e-04 4.62792941e-01 1.19778127e+00]
[0.00221159 0.15154614 1.55821766]
[0.03566427 0.89436804 1.86302895]
[0.04072071 0.05425381 0.87979349]
[0.01263589 0.6573464  2.27661946]
[0.21746646 0.47073725 0.66218816]
[0.05995754 0.33379823 1.14444844]
[0.03624504 0.10490146 1.45306243]
[0.47633837 0.64873606 2.06449357]
[0.01372518 0.39726941 0.76514035]
[0.119547   0.169471   0.94014174]
[0.15039697 0.44329541 1.41679885]
[0.00901386 0.15587613 0.16466548]
[0.01329555 0.97925176 1.35427114]
[0.22189247 0.68633032 1.48591399]
[0.21329899 0.51665818 0.70649879]
[7.64895023e-06 1.03506051e+00 1.16680189e+00]
[0.03915437 0.88176363 1.04223943]
[0.0852927  0.17532606 1.55096867]
[0.21878305 0.5326518  0.88093209]
[0.08226867 0.47581449 1.4272731 ]
[0.12001469 0.40279815 1.019994

[0.29329161 1.05105178 2.01495899]
[0.29410062 0.73276066 1.58863581]
[0.017075   1.07795131 1.27452226]
[0.22548553 0.24272992 0.72502251]
[0.28927206 0.56389185 2.01946499]
[0.11543426 0.46999526 1.15105167]
[0.07301986 0.36329999 0.39367107]
[0.01545695 1.05081966 2.47323113]
[4.41819538e-05 4.72597987e-02 6.45578428e-01]
[0.12679794 0.14514727 0.85294724]
[0.08593553 0.78543347 0.93856916]
[0.13195536 0.28560136 1.10716633]
[0.30012201 0.81906195 1.06924329]
[1.46337969e-04 4.28517667e-01 5.57542771e-01]
[0.10096696 0.27521904 1.18248631]
[4.59650841e-04 7.81587861e-01 1.00831904e+00]
[0.13819835 0.73801883 0.96893059]
[0.4140202  1.3765173  1.71983062]
[0.02977258 0.40661929 1.96081058]
[0.0339882  0.28193447 1.69736047]
[0.06925772 0.64687765 0.91418385]
[2.00350529e-06 1.93930192e-01 1.20237256e+00]
[8.48783550e-04 5.59688928e-01 9.38506582e-01]
[0.08310685 0.37666738 0.49996366]
[0.18629951 1.07092785 1.52430675]
[0.01037479 0.25390793 0.75741541]
[0.38774076 0.55193236 1.14667

[0.03184783 0.556694   1.59563088]
[0.11385062 0.38392763 0.81744894]
[3.52625438e-04 6.38864628e-02 1.30702038e+00]
[0.00425379 0.68266814 1.23504491]
[0.27059211 0.81718162 1.22242381]
[0.04100934 0.3655336  1.49874247]
[0.03990613 0.23465557 2.44550962]
[0.06469704 0.62122776 1.17974032]
[0.09397504 0.09773322 1.27110895]
[0.07073469 0.54032061 0.84157992]
[0.41229567 1.66843393 1.95572533]
[0.02227482 0.20543813 1.06190111]
[0.07573367 0.69032642 1.22249395]
[0.00162555 0.34787497 1.01442386]
[0.00336053 0.4314632  1.41891012]
[0.02919306 0.10471195 1.43572664]
[0.4132908  1.53154325 1.6760289 ]
[0.00294643 0.02901768 1.23185698]
[1.06723721e-04 4.49520423e-01 2.52093873e+00]
[5.90564664e-04 1.14238759e-01 1.41928748e+00]
[0.15561326 0.18044547 1.10508935]
[0.06186117 0.35705826 1.07428855]
[0.01268523 0.3242361  1.11338574]
[0.07317783 0.8948228  1.95858498]
[0.00352563 0.72494662 0.9580853 ]
[0.00087584 0.11988371 0.55264602]
[0.0339735  0.47903649 2.90244453]
[0.11808893 1.42474

[0.01867433 0.30402524 0.68097241]
[0.05672894 0.24589811 0.5895285 ]
[0.07207777 0.46340724 2.74920696]
[3.75273889e-05 3.78132103e-01 1.15134913e+00]
[0.05106536 0.23693541 1.14997785]
[0.04966484 1.10614357 1.40870615]
[0.15960026 0.71115911 1.46306042]
[0.00688075 0.59711114 1.68108318]
[0.02078728 0.05684017 0.82731667]
[0.03649351 0.04856499 1.09043303]
[0.11021813 0.56858084 1.09023361]
[0.00308368 0.41568425 2.3488163 ]
[0.01614837 0.35802495 2.28809502]
[1.06399379 1.47795032 2.18677448]
[0.12677969 0.43310144 0.47563687]
[0.06099334 0.33745961 1.63297339]
[0.06334989 0.06453113 1.56640466]
[0.01333794 1.00995137 1.96326282]
[0.15570514 1.0801654  2.27046323]
[0.03871039 0.10000645 1.73854154]
[0.08429856 0.49609853 1.23892056]
[0.23309111 0.90539248 1.46430858]
[0.01080296 0.03590582 0.46288217]
[5.73721904e-04 3.71141846e-01 1.00732526e+00]
[0.06173508 0.48341154 0.94997116]
[0.02205261 0.94072465 1.15913597]
[0.13901455 0.58466996 0.69017946]
[0.00246056 0.05771832 1.844299